from telebot.handler_backends import State, StatesGroup


class UserState(StatesGroup):
    info_for_task_1 = State()
    chose_times_borders_report_w = State()
    send_task_status_w = State()
    chose_times_borders_status_w = State()
    send_task_status = State()
    chose_times_borders_report = State()
    chose_times_borders_status = State()
    forward_to_worker = State()
    forward_to_manager = State()
    chose_times_borders_w = State()
    chose_times_borders = State()
    chose_task_manager = State()
    chose_task_info_id_worker = State()
    chose_task_info_id_manager = State()
    worker_end_task = State()
    end_task = State()
    send_task = State()
    chose_task_id = State()
    info_for_task = State()
    fin_task_id = State()
    name_worker = State()
    task_name = State()
    to_do_manager = State()
    to_do_worker = State()
    name_manager = State()
    choose_role = State()
